[project]
name = "cs4406m26-assignment1c1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.1",
    "pandas>=3.0.5",
    "pyarrow>=25.0.0",
    "pytest>=9.1.1",
]

[project.scripts]
cs4406m26-assignment1c1 = "cs4406m26_assignment1c1:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
